name: 每日抓取貓咪 API 資料
on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *'

jobs:
  fetch_and_save_data:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' 

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        run: python code.py 

      - name: Upload output files
        uses: actions/upload-artifact@v4
        with:
          name: cat-data-files
          path: |
            cats_data.json
            cats_data.csv
